language: generic

dist: bionic
sudo: required

env:
  global:
  - MAKEFLAGS=-j2
  - PYTHON3=/usr/bin/python3 # avoid /opt/python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y --no-install-recommends python3-cairo python3-pil python3-htmlmin p7zip
- $PYTHON3 --version

script:
- make

before_deploy:
- 7zr a dictionaries-"$TRAVIS_TAG".7z jmdict.mobi jmnedict.mobi combined.mobi

deploy:
  provider: releases
  api_key:
    secure: ADYMOS6UQXiCrnItfzWC8rqLz9pblXymWba2YSOJvyLZQVRoorX9R9mOzMWGIjSDJXpNPfg/yn9jcyFOYFF2lnAKWlZjUUB5375VFTRXl2JtVMmOS7dLsJTCGmor5VWCUlIyrfsIpEO71+q9ml3A+HkKGr+Y4en7W5A0DZdk65Q=
  file_glob: true
  file: dictionaries-*.7z
  skip_cleanup: true
  on:
    repo: jrfonseca/jmdict-kindle
    tags: true
    all_branches: true
